/leonardo_work/CNHPC_1497299/ntriantafyllou/database/database3_venv/venv3/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/leonardo_work/CNHPC_1497299/ntriantafyllou/database/database3_venv/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/leonardo_work/CNHPC_1497299/ntriantafyllou/database/database3_venv/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/leonardo_work/CNHPC_1497299/ntriantafyllou/database/database3_venv/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/leonardo_work/CNHPC_1497299/ntriantafyllou/database/database3_venv/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
